### ISSUE TITLE
[Question] Why add @types to dependencies instead of devDependencies?

### ISSUE THREAD

**Issue by anthonylau** [tediousjs/tedious#1007]
```json
  "dependencies": {
    ...
    "@types/node": "^12.7.11",
    "@types/readable-stream": "^2.3.5",
    ...
```

https://github.com/tediousjs/tedious/blob/ab475d88e900d55989d664d554ed857c8c545a0a/package.json#L45

**Comment by MichaelSun90** [comment]
Hi @anthonylau, 

I found a reference from StackOverflow: https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies.

If a type of module is needed during the runtime and it is placed under devdependencies, Typescript itself cannot really understand what is the type under that module looks like. The stackoverflow link has a simple example. 

If I understand this correctly, "readable-stream" is extended by multiple class definitions under the Tedious project and those classes are exported. If @types/readable-stream is not placed under the dependencies instead of devDependencies, there will be some ambiguity during the run time.

**Comment by IanChokS** [comment]
@anthonylau Please refer to https://github.com/tediousjs/tedious/issues/1008 for your fix.

**Comment by arthurschreiber** [comment]
I moved the dependency on `@types/node` and `@types/readable-stream` to `devDependencies`. This was a mistake on my part - we don't publish type definitions as part of the npm package yet, so we don't need to depend on any other type definitions for now. See https://github.com/tediousjs/tedious/pull/1026
