### ISSUE TITLE
AppService MSI

### ISSUE THREAD

**Issue by redhatva** [tediousjs/tedious#1021]
Has anyone successfully gotten it to work? I have a function app in nodejs using azure-active-directory-msi-app-service and all I get in return is failure to connect - Anonymous.

A good example showing the connection configuration would be handy

**Comment by IanChokS** [comment]
Hey @redhatva, have you checked out our [docs page](https://tediousjs.github.io/tedious/api-connection.html)?

**Comment by MichaelSun90** [comment]
Hi @redhatva,
There is an example of how the connection config looks like:
 { 
  server: "",  
  options: { 
    database: ""
    }, 
    authentication: { 
      type: "azure-active-directory-msi-app-service"
    }
}; 
Maybe give this a try, see if it works?

**Comment by funkydev** [comment]
@redhatva Make sure that you adequately configured SQL Server, especially that you have granted SQL Database access to the managed identity (or app service). You can read more about that [here](https://docs.microsoft.com/pl-pl/azure/app-service/app-service-web-tutorial-connect-msi#grant-permissions-to-managed-identity).

Anyway, I **do not recommend to use integrated authentication onto production environments** because the Node.js **application dramatically slows down**.

**Comment by brandon-svec** [comment]
@funkydev Can you elaborate on your statement regarding performance? Is there any performance testing you can point to? Thanks!

**Comment by birla** [comment]
The authentication works, I haven't tested it in long durations/stress. I'd also like to see evidence that it slows down to node app.
