### ISSUE TITLE
this.userCallback error

### ISSUE THREAD

**Issue by Oscar-Silva** [tediousjs/tedious#1039]
Hi guys,

I have a problem that i tried for 4 hour resolve but i can't resolve this.

well, when i tryed to get a promisse of event request.on("row") i get this erro: 

> node_modules/tedious/lib/request.js:56
>         this.userCallback(err, rowCount, rows);
>              ^
> 

and there is my code: 

```
exports.obter = function () {
    return new Promise((resolve, reject) => {
        var qry = new QRY("SELECT * FROM TabU);
        qry.on('row', function (columns) {
                resolve(columns)
        });

        conDADOS.execSql(qry);
    })
}
```

and i called function:

```
obter.then((a) => {
        console.log(a);
}
```

and then the error occurs

**Comment by arthurschreiber** [comment]
@Oscar-Silva 👋 

The error you're seeing is coming up because the callback argument to the `Request` constructor is non-optional, but it looks like you're not passing a callback function in (`new QRY("SELECT * FROM TabU")`).

So when the query finishes, it tries to call the callback, but it's undefined, and the error you see is thrown.

There is another issue with the way you're trying to wrap the request code with a callback, but that one is less obvious:

By calling `resolve` inside the `row` event listener, you're resolving the promise while the request is still being processed. This can lead to hard to understand bugs. I'd suggest you store the rows emitted through the `row` event in a temporary location, and then resolve or reject the Promise in the callback passed to `Request`, like this:

```js
exports.obter = function () {
    return new Promise((resolve, reject) => {
        var result; // Used to store the result
        var qry = new QRY("SELECT * FROM TabU", (err) => {
          if (err) {
            reject(err);
          } else {
            resolve(result);
          }
        });

        qry.on('row', function (columns) {
          result = columns;
        });

        conDADOS.execSql(qry);
    })
}
```
