### ISSUE TITLE
Request events not firing

### ISSUE THREAD

**Issue by JTraceur** [tediousjs/tedious#1091]
Hey everyone,

I'm trying to figure out why these request events don't get fired?
The `SQLrequest.callback` fires but not the `SQLrequest.on("error")`, `SQLrequest.on("done")` or `SQLrequest.on("requestCompleted")`.

```
    request = new Request(reqString);
    testVar = await requestSQL(request);
```

```
function requestSQL(SQLrequest){

    return new Promise((resolve, reject) => {
        data = null;

        SQLrequest.callback = function (err, rowCount, rows) {
            data = rows;
        }
    
        //Handle error:
        SQLrequest.on("error", function (err) {
            reject("An error occured.");
        });
    
        //Grab data:
        SQLrequest.on("done", function (rowCount, more, rows){
            data = rows;
        });
    
        //Wait until SQL is ready for next request:
        SQLrequest.on("requestCompleted", function () {
            resolve(data);
        });
    
        //Send request to server:
        connection.execSql(SQLrequest);
    });
}
```

**Comment by JTraceur** [comment]
I was able to resolve this issue by inserting a empty function for the request callback on creation:
```
    request = new Request(reqString, () => {});
    testVar = requestSQL(request);
    return testVar;
```
...instead of creating it separately:
```
    request.callback = function (err, rowCount, rows) {
        data = rows;
    }
```
Still seems like weird behavior though?

**Comment by MichaelSun90** [comment]
Hi @JTraceur, for me, personally, I prefer to just pass the callback function as a parameter. At least this could save me few lines of code and the hassles to assign the function to a variable.  

In your case, for creating the call back separately, I guess you may need to do "request.userCallback" instead of  "request.callback". These two variables are kind confusing.  'This.callback' is kind for internal use. If you check the code under Request.ts, you will see for this.callback, there other some steps for emitting different events based on different situations. If you assign a new function to this.callback, then all these events emit logic will be replaced. This could explain why you see some of the events are not fired.  

For the error event, you can see it only emits when the request is used in a prepare and execute mode. You can check here for more detail about that: http://tediousjs.github.io/tedious/api-connection.html#function_prepare
