### ISSUE TITLE
return just data without metadata

### ISSUE THREAD

**Issue by pacmac** [tediousjs/tedious#115]
Maybe I have missed something in the documentation, but is it not possible to execute an SQL statement and only return the column name and values as a dataset and not all of the associated metadata without having to write loops to parse out the column's name and values ?

Is there a configuration / options setting that allows the execSql() to return only the column names and associated values ?

Many Thanks

**Comment by vincebanzon** [comment]
I see that node-mssql is using t-sql. isn't there just something not to include the metadata from the reponse of sql?

**Comment by v-suhame** [comment]
@vincebanzon If question is specific to node-mssql, you can raise the issue in https://github.com/patriksimek/node-mssql, they can help you better.

In tedious, if you don't want metadata, you can ignore [columnMetadata](http://tediousjs.github.io/tedious/api-request.html#event_columnMetadata) event. Metadata is sent as part of SQL Server's response, driver has to parse it in order to reach the row data, so driver will emit `columnMetadata` whenever it gets metadata.
