### ISSUE TITLE
ELOGIN w/ valid login, and connection via PowerShell works fine

### ISSUE THREAD

**Issue by TropicalRaisel** [tediousjs/tedious#1285]
I have the following test:
```javascript
var config = {
  server: 'db-nav',
  authentication: {
    type: 'ntlm',
    options: {
      userName: 'user',
      password: 'pass',
      domain: 'dom'
    }
  },
  options: {
    instanceName: 'inst',
    database: 'debug',
    trustServerCertificate: true,
    trustedConnection: true,
    encrypt: false
  }
}

var Connection = require('tedious').Connection;
var db = new Connection(config);

db.on('connect', function (err) {
  if (err) {
    console.log('Error: ', err)
  } else {
    console.log('Connected!')
  }
});

db.connect();
```
And get this:
```
Error:  ConnectionError: Login failed for user 'DOM\user'.
```

Initially `encrypt` wasn't present, and I got a `ConnectionError - 16840:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1994`. The 
`TCP/IP` feature on the database is enabled. Any ideas as to what's happening?

**Comment by arthurschreiber** [comment]
There might be multiple issues you're running into here.

> Initially `encrypt` wasn't present, and I got a `ConnectionError - 16840:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1994`.

This sounds like you're able to connect just fine, but the SSL/TLS handshake fails because the client does not support the tls/ssl protocol used by the server.

This is most likely because you try to connect to an "old" version of SQL Server, or the Windows version that SQL Server is running on is outdated. Can you provide the exact versions of both?

Specifying `encrypt: false` allowed you to open a connection, but it also means that communication will be unencrypted, and if someone can listen to the traffic on your network, they'll be able to intercept the username and password easily - so that's not really recommended.

The `ConnectionError: Login failed for user 'DOM\user'.` error means that either the password you specified was incorrect, or there is a bug in our domain authentication code. 🤔

**Comment by TropicalRaisel** [comment]
It was an issue on the database end. Something with user groups.
