### ISSUE TITLE
List of IDs as Parameter

### ISSUE THREAD

**Issue by tcs-apeters** [tediousjs/tedious#130]
How do I add the parameter for a list of IDs. The following is not working. 
Do I need to create a parameter for each value in the list?

var sql = 'select name from address where id in (@id)';
request.addParameter('id', TYPES.Int, '42,38,5');

Any solutions?

**Comment by GISDev01** [comment]
I had a similar issue and this is how I solved it if anyone wants a starting place for how to implement this in a quick and dirty way (anything is better than allowing SQL Injection). It does require looping through an array twice due to how my code is set up (this code is truncated), but in my use case the arrays are quite small so it's no big deal.

`
//this input Ids string is something like 1000,1002,1005
var IDsArr = Ids.split(',');
//this string will go in your SQL Query Statement with string concatenation
var IDs_InParameterizedStr = "";

//loop through the first time to build a quick string e.g. "@paramId0, @paramId1"
IDsArr.forEach(function (element, index, array) {
	IDs_InParameterizedStr += '@paramId' + index + ',';
});

//remove trailing comma in the parameterized string
//quick workaround to not have to conditionally add the comma
IDs_InParameterizedStr = IDs_InParameterizedStr.slice(0, -1);

var sqlStrParameterized = "SELECT * FROM tablename WHERE " +
  "factor_id IN (" + IDs_InParameterizedStr + ")";
  
//now we set the params to their correct values based on the input Ids from the beginning
IDsArr.forEach(function (element, index, array) {
	request.addParameter('paramId' + index, TYPES.Int, IDsArr[index]);
});
`

**Comment by richardbarrell-calvium** [comment]
`OPENJSON` can be used to unpack multiple values too. e.g. selecting multiple rows from a table by ID can look like:

```
var ids = [1,2,3];
var sql = `WITH ids_cte(id) AS (SELECT value FROM OPENJSON(@ids))
SELECT tablename.* FROM tablename INNER JOIN ids_cte ON tablename.id = ids_cte.id`;
request.addParameter('ids', TYPES.NVarChar, JSON.stringify(ids));
```

(Please excuse errors in the above, I typed it mostly from memory.) This is nice for passing a sequence of strings/nvarchars because you don't need to worry about what happens if a value could legitimately have a comma (or whatever separator character you use) appear in it. I'm not really sure how well or poorly this approach performs; I've only used this approach in API endpoints that currently get no more than a dozen requests per minute.

**Comment by conradoramalho** [comment]
What is the best solution for this problem?

Is it possible to pass multiples ids?

**Comment by prasanthtootcat** [comment]
Is there any new solutions for this?

**Comment by cepm-nate** [comment]
It does indeed seem odd that in 2020 there is no standard way to send a variable number of values from javascript -> SQL for use with the the IN() operator. I could use a TVP or stored procedure and split strings, but it all seems rather hacky.
