### ISSUE TITLE
How do I remove the "JSON_" key in front of responses that were formatted with "FOR JSON PATH"

### ISSUE THREAD

**Issue by NamedArray** [tediousjs/tedious#1363]
I'm executing a stored procedure which contains a select statement that uses `for json path, root('error')` and returns info if an error was raised.

I get this: `{JSON_F52E2B61-18A1-11d1-B105-00805F49916B: '{"error":[{"ErrorNumber":50…"`
Instead of this:  `'{"error":[{"ErrorNumber":50…"`

Is there a driver option to remove that exterior "JSON_" wrapper?

**Comment by MichaelSun90** [comment]
Hi @NamedArray, I have never tried a store procedure like this before, can you provide some steps with an example procedure, so I could try to reproduce this behavior locally? See if I can find where the driver has this prefix added to the response or this behavior is actually the expected behavior. To my knowledge, I do not believe I have seen any configuration that could be used to resolve this on the driver side. There is also a [**page**](http://tediousjs.github.io/tedious/) for the configurations that the driver supported, you can also check there, see if there is anything that helps.

**Comment by NamedArray** [comment]
@MichaelSun90 

Long story:  I'm using the `knex` query library, which itself is using `tedious`.  `knex` too, receives the `JSON_prefix`.

For context, I'm trying to create a class in JavaScript that interacts with SQL and ultimately represents my "Model".  The problem is, I'm required to use Stored Procedures... I'm not allowed to use an ORM because I would have to grant permissions to tables. :(

Ultimately, I think the mandate for me to use Stored Procedures pretty much negates any hope and dream I had of creating a model class for my data. (My model *is* the Stored Procedure --- I can do all the "data formatting" there.)

Still, I often use `for json path`, as shown in the example below.  Anytime you use `for json path`, KNEX and Tedious will prefix the response with `JSON_`.  If somebody wanted to do a `for json path`, they're going to want an unmodified response from SQL -- they're not going to want that `JSON_` prefix.

_In the example below, I was trying to capture an error in a try/catch block, but I later learned that `knex` actually handles `raiserror` from a Stored Procedure without the need for a try/catch statement_

```
SELECT
	ERROR_NUMBER() AS ErrorNumber
	,ERROR_STATE() AS ErrorState
	,ERROR_SEVERITY() AS ErrorSeverity
	,ERROR_PROCEDURE() AS ErrorProcedure
	,ERROR_LINE() AS ErrorLine
	,ERROR_MESSAGE() AS ErrorMessage
for json path, root('error')
```

**Comment by MichaelSun90** [comment]
Hi @NamedArray,Thank you for all the details. 
Just run a query using Sql Server Management Studio with a 'for Json' key word : "select  colname from table for json path" . In my result set, it also has a 'JSON_' prefix. Could this be a common behavior for  this key word, and not caused by tedious? 
This is screen shot for my output : 
![image](https://user-images.githubusercontent.com/47126816/143084939-ae971fb0-5447-4a70-95c0-3234f1aa3bdd.png)

I also found a page from Microsoft doc that related to this: https://docs.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server?view=sql-server-ver15 .  The examples in this page also includes the 'JSON_' prefix.

**Comment by arthurschreiber** [comment]
👋 @NamedArray

`JSON_F52E2B61-18A1-11d1-B105-00805F49916B` is the column name that SQL Server uses to send back JSON data, and as you noticed, the data is sent back as a regular string.

If you want to actually use this data in your application, you need to pass the string to `JSON.parse` as part of your query result handling. Automatic handling for this won't be added to `tedious`, because we can't know what the user's intentions are, and serializing JSON is a rather expensive operation.

Please let us know if you have any further questions. 🙇‍♂️

**Comment by NamedArray** [comment]
Wow! I had never previously noticed that in SQL Management Studio.
