### ISSUE TITLE
Error while using mssql

### ISSUE THREAD

**Issue by guru-singh1** [tediousjs/tedious#1367]
am using MSSQL in nodejs app,

Below code

const sql = require("mssql");
Is throwing

iisnode encountered an error when processing the request.

HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1002
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The last 64k of the output generated by the node.exe process to stderr is shown below:

Application has thrown an uncaught exception and is terminated:
C:\Inetpub\vhosts\deepassessment.in\httpdocs\node_modules\tedious\lib\token\stream-parser.js:85
  static async *parseTokens(iterable, debug, options, colMetadata = []) {
 
       

SyntaxError: Unexpected token *
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:617:28)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (C:\Inetpub\vhosts\deepassessment.in\httpdocs\node_modules\tedious\lib\token\token-stream-parser.js:10:44)
Quite sure it’s something to do with drivers but can’t make out

Kindly advise

Btw it’s working fine on local and heroku server but not working on shared server

**Comment by MichaelSun90** [comment]
Hi @guru-singh1 , from your description, Seems the error message "You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'." says that some settings on the iisnode affect the request behavior. In addition, you posted that the http status is 500, and this error message says "http 200". Which one is the actual return http status code? 
Can you please share your connection configuration for mssql and I am not quite sure where does iisnode fits in this setup? By the way, what version of mssql and tedious you are using for this project?

**Comment by arthurschreiber** [comment]
Hey @guru-singh1,

the current version of `tedious` requires at least Node.js 12 to run, because we're using JavaScript language features that were added in that version. I've no experience with `iisnode`, but it looks like it's running with an outdated version of Node.js.

You could try using older versions of `tedious` (as they supported older versions of Node.js), but you should know that those are unsupported and you might encounter bugs that have been fixed in newer versions.

**Comment by guru-singh1** [comment]
yes, with higher version of nodejs i am able to connect, 
current version 18.18
many thanks.
