### ISSUE TITLE
FOR JSON PATH truncated results

### ISSUE THREAD

**Issue by morningtundra** [tediousjs/tedious#1369]
In SQL Server 2016, it [seems](https://stackoverflow.com/questions/51087037/sql-server-json-truncated-even-when-using-nvarcharmax) [the ](https://stackoverflow.com/questions/54973536/for-json-path-results-in-ssms-truncated-to-2033-characters/54973676) [results ](https://stackoverflow.com/questions/46327765/sql-server-truncates-data-returned-as-json?noredirect=1&lq=1)are being truncated. 

What is the recommended way to handle this in tediousjs?

**Comment by arthurschreiber** [comment]
Hey @morningtundra,

is this truncation happening in these other libraries / clients because of the value of the `TEXTSIZE` setting? `TEXTSIZE` is used to configure the length of text types (including `nvarchar(max)` that is used for JSON data).

In `tedious`, the `TEXTSIZE` is set to `2147483647` by default - so `nvarchar(max)` values can be up to 2GB in size. This should be large enough that truncation should not happen. I haven't tested this out - please let us know if you run into any truncation issues. 🙇‍♂️
