### ISSUE TITLE
Error ESOCKET - Could not connect (sequence) on Centos 7

### ISSUE THREAD

**Issue by edwinspire** [tediousjs/tedious#1373]
Kind regards.
I have been using TEDIOUS for a long time on various projects successfully. However now I have an application that connects to about 1000 windows SQL Servers, but my problem is specifically with 5 servers.
On my windows machine it connects perfectly, but when I upload my application to the CENTOS 7 production server it gives me connection problems only on those 5 servers.

The connection parameters and the error message I have is the following:

Config:  {
  server: '192.168.XXX.XX',
  options: {
    encrypt: false,
    requestTimeout: 900000,
    connectTimeout: 60000,
    debug: { packet: true, data: true, payload: true, token: true, log: true },
    database: 'msdb',
    useColumnNames: true,
    rowCollectionOnDone: true,
    trustServerCertificate: false,
    rowCollectionOnRequestCompletion: true
  },
  authentication: {
    options: { password: 'pwdinicial', userName: 'sa' },
    type: 'default'
  }
}

State change: Initialized -> Connecting
Failed to connect to 192.168.122.98:1433 - Could not connect (sequence)

![image](https://user-images.githubusercontent.com/3129446/145684328-4022563b-baae-4ee9-98ed-be0fb3b44786.png)

As I said before, from my machine (Windows 10) it works perfectly, but from the production server (Centos 7) they only work with 995 servers out of the 1000 that I have.
This is the version of the packages that I have on my machine:

Windows 10 64Bits
  node: '14.15.4',
  v8: '8.4.371.19-node.17',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '83',
  nghttp2: '1.41.0',       
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1i',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'

And this is the production machine:

Centos 7 64Bits
  node: '14.17.6',
  v8: '8.4.371.23-node.76',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1l',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'

One of the servers that I connect to from windows but not from Centos is:

Microsoft SQL Server Standard (64-bit)
Windows Server 2016 Standard (10.0)

![image](https://user-images.githubusercontent.com/3129446/145684064-16f5420e-d560-4f8d-a389-7bf1825a47bb.png)

If someone can guide me it will be of great help.
Greetings from Ecuador.

**Comment by arthurschreiber** [comment]
Can you try using the same Node.js version on your Windows machine and see what happens? Another thing to try would be to setup a CentOS 7 VM and try to connect from there to one of those SQL Server machines.

The error message means that opening the socket failed (before any data was send from `tedious` to SQL Server). This means this has nothing to do with things like TLS configuration or anything like that, which would've been my first guess otherwise.

You could try adding some log output here:

https://github.com/tediousjs/tedious/blob/b2d0fa20d6aa9118ccd0aaf8235b6793bf02aff3/src/connector.ts#L136-L145

The contents of the `_err` argument of this callback could help you to pinpoint what's going on. We should be wrapping the low level socket error into an `AggregateError` together with our error to give users better error information, but we don't do that unfortunately.

If you can get ahold of the actual error message, please add it to the issue here. 🙇‍♂️

**Comment by edwinspire** [comment]
Thank you for answering, you did not give me the solution but you indicated the direction to take. I put the logs and when doing the tests I noticed a pattern, all the servers that I cannot connect to are within the 192.168.122.X segment, which makes me suppose that there is some restriction to that segment. I'm going to attack from that side.
Thank you again and I will be telling you what the result was.

**Comment by edwinspire** [comment]
Well, I found that in Centos 7 when restarting the server a network card is raised in that network segment, once deactivated with the command:

![image](https://user-images.githubusercontent.com/3129446/145698181-d30c0fdd-a59a-45c8-a53b-aa7a1e4353d7.png)
sudo ip link set dev virbr0 down

The problem was solved.
I close the case, it was not because of TEDIOUS.
