### ISSUE TITLE
`.connect` can not be called on a Connection in `Connecting` state.

### ISSUE THREAD

**Issue by martnjf** [tediousjs/tedious#1375]
Hello everybody, I'm currently working in a Node JS project using Tedious, this is a function, that loops another function to insert data.
## My issue
The issue is that when I run my code for my ```insertOffice()``` just once, it works perfectly, but when I run it in the loop, I get the following error:

```
..:\...\node_modules\tedious\lib\connection.js:993
      throw new _errors.ConnectionError('`.connect` can not be called on a Connection in `' + this.state.name + '` state.');
            ^
ConnectionError: `.connect` can not be called on a Connection in `Connecting` state.
```
## What I expect
Using the documentation I saw around here, I expect my project to run my ```insertOffice()``` twice and send each time ```index```

## My Code

```
var connection = new Connection(config);
function insertOffice(index) {
    // console.log(index)
    connection.on("connect", function (err) {
        console.log("Successful connection");
    });
    connection.connect();

    let url = `https://api.openweathermap.org/data/2.5/weather?lat=${data2[index].latjson}&lon=${data2[index].lonjson}&appid=${api_key}&units=metric&lang=sp`;
    fetch(url)
        .then((response) => { return response.json(); })
        .then(function (data) {
            var myObject = {
                Id_Oficina: data2[index].idoficina,
                Humedad: data.main.humidity,
                Nubes: data.clouds.all,
                Sensacion: data.main.feels_like,
                Temperatura: data.main.temp,
                Descripcion: data.weather[0].description,
            };
            console.log(myObject);
            const request = new Request(
                "EXEC USP_BI_CSL_insert_reg_RegistroTemperaturaXidOdicina @IdOficina, @Humedad, @Nubes, @Sensacion, @Temperatura, @Descripcion",
                function (err) {
                    if (err) {
                        console.log("No se pudo insertar dato, " + err);
                    } else {
                        console.log("Dato con id de Oficina: " + myObject.Id_Oficina + " insertado con éxito.")
                    }
                }
            );
            console.log(myObject.Id_Oficina)
            request.addParameter("IdOficina", TYPES.SmallInt, myObject.Id_Oficina);
            request.addParameter("Humedad", TYPES.SmallInt, myObject.Humedad);
            request.addParameter("Nubes", TYPES.SmallInt, myObject.Nubes);
            request.addParameter("Sensacion", TYPES.Float, myObject.Sensacion);
            request.addParameter("Temperatura", TYPES.Float, myObject.Temperatura);
            request.addParameter("Descripcion", TYPES.VarChar, myObject.Descripcion);

            request.on("row", function (columns) {
                columns.forEach(function (column) {
                    if (column.value === null) {
                        console.log("NULL");
                    } else {
                        console.log("Product id of inserted item is " + column.value);
                    }
                });
            });
            request.on("requestCompleted", function () {
                connection.close();
            });
            connection.execSql(request);

        });
}

function functionLooper() {
    for (let i = 0; i < 2; i++) {
        let response = insertOffice(i);
    }
}

functionLooper();
```

I can't understand why when I don't run my code in a loop it works but when I do it in a loop it doesn't, here's my stackoverflow [question](https://stackoverflow.com/questions/70358386/how-can-i-insert-multiple-times-data-in-sql-server-by-running-the-inserting-func) that details my problem a little bit more.

**Comment by MichaelSun90** [comment]
Hi @martnjf, If I understand your code correctly, that you want to loop through multiple requests, right?

Something that you can try is:  move your connection-related operations outside of your interoffice(index). Then close the connection after all the requests are finished after functionLooper().  This will only close the connection when all the requests that you want to send are finished, and it only calls the .connect once, so you do not need to worried the same error will occur.

However, there is a thing that you need to be careful is, when you loop through your requests, you have to make sure that only when a previous request is fully finished, then you can proceed to the next request due to the protocol. You can find a bit more information under this title "Requests can only be made in the LoggedIn state, not the SentClientRequest state" from this page http://tediousjs.github.io/tedious/frequently-encountered-problems.html

If you want, you can also use multiple connections for your code. Each connection will only handle a single query.  For doing this, just move the line: var connection = new Connection(config); into you interoffice(index) should do. This change will create a new connection object for each loop iteration, so no conflict should occur. You may want to give each connection object a new name though. Even javascript allows objects to share the same name, it is better to distinguish between objects. 

The error that you are getting is because the connection may not yet reach its end state for your first loop iteration, the .connect call from the second iteration may have already been called on the same connection object. Therefore, an error occurs.

**Comment by martnjf** [comment]
It worked @MichaelSun90 Thank you very much!

**Comment by MichaelSun90** [comment]
No problem. I will close this issue then.
