### ISSUE TITLE
Date Issue

### ISSUE THREAD

**Issue by ptrckc** [tediousjs/tedious#143]
After upgrading to the latest release of node-mssql (https://github.com/patriksimek/node-mssql), which is now using "tedious": ">=0.2.1", Date's are coming back with time information.

I know the option "useUTC" was added. This properly changes DateTime's. Example:

Previously: "2014-04-01T21:26:46.966Z"
Now: "2014-04-01T16:26:46.966Z" (useUTC: true)
         "2014-04-01T21:26:46.966Z" (useUTC: false)

However, for the Date issue, I see the following:

Previously: "2014-02-05"
Now: "2014-02-05T00:00:00.000Z" (useUTC: true or false)

As you can see, the time information doesn't not properly reflect the change between returning dates in UTC or not.

**Comment by aart-janboor** [comment]
Is there any way the libary can be changed to support proper date display for tedious > 7.2? It's kind of lame to show the users "T00:00:00.000Z" for every date (in SQL server this is a real DATE field, so there is no time data at any time). I recognize that it's nice to return JavaScript date objects - but in many use cases you simply send the result from the query to the browser in JSON and hence those nice JS date objects are converted to strings like "1995-05-15T00:00:00.000Z" which make no sense to the user.

**Comment by CenterStoneOSD** [comment]
In my opinion it is not the job of a connector to format data. We just pipe the output through a formatter stream that formats date or date time fields to whatever is appropriate for the use case at hand.

**Comment by rossipedia** [comment]
I have to agree with @CenterStoneOSD. The most logical representation for Date/Time data is a JavaScript Date object. If you need more fine-grained control over formatting when displaying to the user, you can use something like [moment.js](http://momentjs.com)

**Comment by aart-janboor** [comment]
The problem I have with the JavaScript Date object that in fact it is not a Date object but rather a DateTime object. It can be created without adding the time information but JavaScript then populates these fields implicitly with 00:00:00 (instead of NULL, which would be closer to reality). I feel a database connector library should represent the values stored in the database as closely as possible and should not add or modify any data, hence I believe the Javascript Date object is not a good representation of the SQL server Date field type which does not contain any time information. 

As an alternative you could use the YYYY-MM-DD string representation which is also common in other database connectors and database management tools like SQL server management studio. 

I believe in C# there is a similar situation, there is no native Date object available in the language and hence if you read a date column using the SqlDataReader class by default it will provide a number (internal SQL data representation). You can also render it as string or optionally as a DateTime object with the 00:00:00 time implicitly added. This could also be a good solution and would align the libraries making it easier to switch between them.

**Comment by rossipedia** [comment]
The difference between a date and a time is completely arbitrary. Both are essentially nothing more than a notation of a unit in time. 

> JavaScript then populates these fields implicitly with 00:00:00 (instead of NULL, which would be closer to reality)

I think you misunderstand how a JavaScript `DateTime` object is represented. It is a single value: 

> Date objects are based on a time value that is the number of milliseconds since 1 January, 1970 UTC.

(From the MDN docs here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date). 

As it is a core, standardized JS type, a database connector should use that type to represent date and/or time information. Having a custom type in one case (date-only) would violate the [Principle of Least Astonishment](http://en.wikipedia.org/wiki/Principle_of_least_astonishment), confusing new users of the library and requiring them to learn that type and it's rules _specifically for Tedious_. This is counter-intuitive.

>  I feel a database connector library should represent the values stored in the database as closely as possible

Functionally, the JS `Date` object does everything this. It can represent both a SQL `Date` type and `DateTime` type with equal accuracy. The issue here seems to be one of formatting or user interface, which is not the responsibility of Tedious.

**Comment by aart-janboor** [comment]
Ok thank you for your consideration.

**Comment by GlobalJet** [comment]
Actually, if in my query I wrote "CAST(myDate AS DATE)", Tedious should return a date object at least, and formated. There is no excuse...

I get a string... and it's a DATE in SQL SERVER.
