### ISSUE TITLE
 request.on('done',  ) Not working

### ISSUE THREAD

**Issue by hasan3ysf** [tediousjs/tedious#379]
Hi,
I wrote the below statement to be executed once the SQlexec is DONe, but got nothing!

`request.on('done', function (rowCount, more, rows) {console.log(rowCount + ' rows final'); });`

my configuration is defined as:

```
    var config = { 
       userName: 'sa',
       password: 'myPswd',
       server: 'myIP',
       options: {
            database: 'myDB',
                rowCollectionOnRequestCompletion: true,
                  rowCollectionOnDone: true
         },
    };
```

**Comment by seanpoulter** [comment]
I can recreate this problem running the [minimal example](https://github.com/pekim/tedious/blob/master/examples/minimal.js#L58) connecting to SQL Server 2012.

**Comment by codyaweber** [comment]
I'm fairly new to tedious, so forgive me if this is way off. But I think this (from [docs](http://pekim.github.io/tedious/api-connection.html#function_execSql)) could be causing a problem:

"As `sp_executesql` is used to execute the SQL, if the same SQL is executed multiples times using this function, the SQL Server query optimizer is likely to reuse the execution plan it generates for the first execution."

I think 'reusing the execution plan' means the query gets treated as a stored procedure, so instead of the `done` event being called upon completion, `doneProc` and `doneInProc` get called. Using `execSqlBatch` as opposed to `execSql` would fix this. Not sure if there's a more appropriate way to prevent the server from treating the query as a stored procedure though.

**Comment by RaduGrama** [comment]
@codyaweber, you are correct and all workarounds you suggested address the issue, with `doneProc` or `doneInProc` probably being the better workarounds. This should probably be considered a documentation bug.

**Comment by arthurschreiber** [comment]
Yes, this is a documentation bug. The `done` event is not always fired. There's been quite a few issues regarding this. Patches for fixing the documentation would be very welcome.

**Comment by veleek** [comment]
Excuse me if this seems like a ridiculous question, but where IS the documentation located?  I was going to try and update this, but I don't know where the update should go.

**Comment by codyaweber** [comment]
It seems the link I posted earlier has changed.

http://tediousjs.github.io/tedious/api-request.html
