### ISSUE TITLE
SQL Server 2012 ECONNREFUSED

### ISSUE THREAD

**Issue by adviner** [tediousjs/tedious#65]
Using latest nodejs and tedious versions and the following code:

var Connection = require('tedious').Connection;
var Request = require('tedious').Request;

var config =
{
    server: '192.168.1.113',
    userName: 'myUserName',
    password: 'myPassword',
    options:
    {
        database: 'MyDatabase',
        port: '1433',
        encrypt: true,
        driver: 'SQL Server Native Client 11.0'
    },
    debug:
    {
        packet: true,
        data: true,
        payload: true,
        token: true,
        log: true
    }
};

var connection = new Connection(config);

connection.on('connect', connected);
connection.on('infoMessage', infoError);
connection.on('errorMessage', infoError);
connection.on('end', end);
connection.on('debug', debug);

function connected(err)
{
    console.log('connected=> ' + err);
}

function infoError(info)
{
    console.log('infoError=> ' + info);
}

function debug(message)
{
    console.log('debug=> ' + message);
}

function end()
{
}

I get the following error after i run it:

node test_sqlserver_tedious.js
debug=> connection to 192.168.1.113:1433 - failed Error: connect ECONNREFUSED
debug=> State change: Connecting -> Final
debug=> connection to 192.168.1.113:1433 closed
debug=> State change: Final -> Final

Any ideas?  I could help you test the source if you show me how.

Thanks

**Comment by Beniy** [comment]
Dear Experts,
I have faced same error but the problem is my error is happenning after a connection is established and it's inserting big files to database, I do not have any issue with small files:

adding data to databse
getting columns from db
got table columns successfully
adding rows to DB
rows inserted succesffuly
adding data to databse
getting columns from db
got table columns successfully
adding rows to DB
rows inserted succesffuly
adding data to databse
getting columns from db
got table columns successfully
adding rows to DB
rows inserted succesffuly
adding data to databse
getting columns from db
got table columns successfully
adding rows to DB
 { [ConnectionError: Failed to connect to localhost:1433 - connect EADDRINUSE 127 .0.0.1:1433] name: 'ConnectionError', message: 'Failed to connect to localhost:1433 - connect EADDRINUSE 127.0.0.1:1 433', code: 'ESOCKET' }

Your support is appreciated.

**Comment by arthurschreiber** [comment]
@Beniy Do you have example code that we can use to reproduce this?

**Comment by Beniy** [comment]
Dear Arthurschreiber,
Actually the problem cannot be related to code because sometimes it is parsing text file and inserting to db but sometimes it's showing that error, even with same file and same condition but in different time.
I want to know any other dependencies to this task?

Thanks
