### ISSUE TITLE
connection to sql server 2000 from mssql library and i cant set LEVEL SEVERITY

### ISSUE THREAD

**Issue by nick9015** [tediousjs/tedious#666]
Hi,

I am try to init connection to sql server 2000 from mssql library and i cant set LEVEL SEVERITY.

My config:

> const config = {
> 	server: 'x',
> 	user: 'x',
> 	password: 'x',
> 	options: {
>         tdsVersion: '7_1'
>     },
> 	requestTimeout: 60000 
> };
> const pool = new mssql.ConnectionPool(config,function(err){
> 	if (err) {
> 		console.error(err);
> 		return;
> 	}	
> });

Helpme please?

Thank you

**Comment by nick9015** [comment]
Hi, thanks for you response. I need migrate multiples scripts(1000K).  I want simulate this(php script):

> 
> // Connect to MSSQL
> mssql_connect('KALLESPC\SQLEXPRESS', 'sa', 'phpfi');
> 
> // Set the minimum message severity to 17, this
> // will not show any messages issued by the underlaying
> // API when we select a non-existent database below
> **mssql_min_message_severity(17);**
> 
> // Select a non-existent database
> mssql_select_db('THIS_DATABASE_DOES_NOT_EXISTS');
> 

Thank you

**Comment by arthurschreiber** [comment]
If I'm understanding the PHP docs correctly, `mssql_min_message_severity` changes the MSSQL driver's settings to ignore informational messages below the given severity. 🤔

In `tedious`, these informational messages are exposed via the `info` callback on `Request` objects. If you don't intend on listening for this callback, there is nothing you need to do. Otherwise, the argument passed to the callback will have a `.class` property that you can check and act accordingly. I hope this helps you along! 🙇 

Closing this as this is not really about an issue with tedious. 😁
