### ISSUE TITLE
Int comes as String in resulting rows

### ISSUE THREAD

**Issue by rok-star** [tediousjs/tedious#699]
Hi

Int values come as String in resulting rows. Is there any option for that or it is default behaviour?

here is one cell from rows:
`{ value: '1',
  metadata: 
   { userType: 0,
     flags: 17,
     type: { id: 38, type: 'INTN', name: 'IntN', dataLengthLength: 1 },
     colName: 'type__id',
     collation: undefined,
     precision: undefined,
     scale: undefined,
     udtInfo: undefined,
     dataLength: 8,
     tableName: undefined } }`

Thanks

**Comment by arthurschreiber** [comment]
This happens on `bigint` columns, because 'bigint's can contain values outside of the range of JavaScript's `number` type.

There is a set of different libraries for javascript that allow you to work with these kinds of numbers, but the rest of your application needs to understand them as well.

Examples:

* https://www.npmjs.com/search?q=big+integer
* https://www.npmjs.com/search?q=big%20number

Unforunately, to write these values back into the database you'll have to insert them as `char`/`varchar`/`nchar`/`nvarchar` and rely on SQL Server type conversion.

We're working on improving this situation and allowing you to define your own conversion method from/to TDS data types in the future.

**Comment by rok-star** [comment]
arthurschreiber, Thank you for quick response.
