### ISSUE TITLE
tedious versioning housekeeping/confusion

### ISSUE THREAD

**Issue by jimmont** [tediousjs/tedious#750]
On master [package.json lists the version as `0.0.0-dev`](https://github.com/tediousjs/tedious/blob/master/package.json#L30).

the [npm published version is `2.6.1`](https://www.npmjs.com/package/tedious)

From the list of available releases and tags there is a version `2.6.2`
https://github.com/tediousjs/tedious/releases
https://github.com/tediousjs/tedious/tags

It would be helpful to keep these items in sync. If this does not fit a desired workflow please make it clearer as to where this information is provided. As to published modules is there a reason it is out of sync with the project?

**Comment by Hadis-Fard** [comment]
@arthurschreiber I was looking at ways to sync the versions and automate it, do you know what's the reason of changing the semantic release script to just semantic release in https://github.com/tediousjs/tedious/commit/b092fc731601a091a9df8f3c26155d5c603a5cd2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L75 ? I guess it is because of the migration note in [v12.0.0 ](https://github.com/semantic-release/semantic-release/releases?after=v12.2.1) where travis-deploy-once is mentioned"
```
"scripts": {
    "semantic-release": "semantic-release",
    "travis-deploy-once": "travis-deploy-once"
  }
```
but it is not saying anything about changing the semantic-release script. looking at https://github.com/semantic-release/semantic-release/compare/v11.2.0...v12.0.0  I don't see changes to the publishing as well. So I think we should revert the changes back to `semantic-release": "semantic-release pre && npm publish && semantic-release post"`. What do you think?

Also do you know why is the version in package.json 0.0.0-dev and not in sync with github and npm?

I also looked into automating `next` and `latest`, the usual [workflow](https://github.com/semantic-release/semantic-release/issues/381#issuecomment-296246628) to do so is to have two branches `dev` publishing `next` and `master` publishing stable `latest`, which seems two much overhead for us, and I believe automating it based on the time frame can't be done through semantic-release packaging since the semantic-releases are based on triggering config on github.
