### ISSUE TITLE
Incorrect syntax near the keyword 'with'

### ISSUE THREAD

**Issue by nkolli45** [tediousjs/tedious#898]
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previousstatement must be terminated with a semicolon.

**Comment by MichaelSun90** [comment]
Hi @navinkolli, can you provide the place that presents this behavior? Thanks

**Comment by IanChokS** [comment]
@nkolli45, Can you provide some more details for us?

**Comment by BlueTalon6** [comment]
Had the same error with a BulkLoad. Updated tedious and got a second, more informative error pointing to the tableName parameter. Turns out I was using a SQL reserved word for my table name. Enclosing in brackets fixed it but have since changed the table name.
`const bulkLoad = connection.newBulkLoad('[option]', options, function (error, rowCount) { .. `

Could close out as the error reporting has improved, OP could point to a different issue though..

**Comment by MichaelSun90** [comment]
Hi @BlueTalon6 , Thanks for sharing this. Will close this for now.
