### ISSUE TITLE
connection lost 

### ISSUE THREAD

**Issue by Paisansang** [tediousjs/tedious#906]

**Comment by MichaelSun90** [comment]
Hi @Paisansang, can you provide some description for the issue? Thanks

**Comment by Paisansang** [comment]
Thak for support.
I got error form teious and crash node...

MSSQL Connect err... ConnectionError: Failed to connect to upfrontpim.net:1433 in 5000ms
Failed to connect to  xxxx  in 5000ms
[nodemon] clean exit - waiting for changes before restart
......
How can I handle error that dont crash Node ??
Thanks.

---my module is : 
function   getMsQuery(sql,callback){
  //console.log(sql);
	
	var Connection 	= require('tedious').Connection;
	var Request 	= require('tedious').Request; 
	var dbName		= msConfig.dbName;
	  var resp ={
				dbcode:999,
				dbmessage:"ERROR",
				dbfields:null,
		   		dbitems:null
		   };
	  
	var config = {
	    server: msConfig.host, //"vpn.upfront.co.th",
		char_set:"utf8",
	    options:msConfig.options,
	    authentication: {
			    type: "default",
			    options: {  
			        userName: msConfig.userid, //"upfdba",
			        password: msConfig.password //"upfrontadmin"
			      }
				 }
	     }

 var connection = new  Connection(config); 
	
	connection.on('error'
      , function(err) {
				//console.log("MSSQL Connect err...\n"+err);
			    ecode=999;
			    emsg=err;
			    
		    	 resp.dbcode	=ecode;
				 resp.dbmessage	=emsg; 
				// callback(resp);
			     return;
	        });
	 
  connection.on('end',function(){
	 // console.log('connection end');
	 // callback(resp); 
  });
  
  connection.on('connect'
	, function(err) {
		if(err){
			  console.log("MSSQL Connect Err... "+err);
			  resp.dbmessage=err.message;
			  callback(resp);
			  return;
			}
		else { 
    var results = []; 
    var fields	=[];
    var ecode =0;
    var emsg="OK";
    var rqerr="0";
    
    var request = new Request(sql
			,function(err, rowCount,rows) {
			  if (err) {
				 // ecode	=err['number']; //???No such value
				  emsg	=err['message'];
				  rqerr =emsg;
			      console.log('Ms Req Error ..'+err);
			      //---wait for event on error to report Error >>>
			      
			  } else {
				//  console.log('Read db '+ rowCount + ' rows');
		    	//  callback(resp);
		   		 // connection.close();
				}
			});
    
    	request.on('columnMetadata', function (columns) { 
    		var item = {}; 
			columns.forEach(function (column) { 
				item[column.colName] =column.type.name;
			
				}); 
			fields.push(item); 
    	});
    	
      request.on("row", function (columns) { 
			var item = {}; 
			columns.forEach(function (column) { 
				item[column.metadata.colName] =column.value
				}); 
				results.push(item); 
		    }); 
 
      request.on('requestCompleted',function(){
    	  if(rqerr!='0'){
    			 resp.dbcode	=888;
    			 resp.dbmessage	=rqerr; 
    	  }
    	  else { 
	    	 resp.dbfields	=fields;
	    	 resp.dbitems	=results;
	    	 resp.dbcode	=ecode;
			 resp.dbmessage	=emsg;
	    	  }
    	  //console.log('MsQuery Completed with '+resp.dbcode);
    	  callback(resp);
   		  connection.close();
      	}); 
      connection.execSql(request);
		}
	});

};

**Comment by MichaelSun90** [comment]
Hi @Paisansang, I am not sure that I understand the situation correctly. You encountered a connection error from the tedious side, and the program crashed, right? If you want to prevent the error and keep the program running, you can use a try-catch block to consume the error internally and handle it in the way that you want.

**Comment by arthurschreiber** [comment]
> If you want to prevent the error and keep the program running, you can use a try-catch block to consume the error internally and handle it in the way that you want.

I don't think a try-catch block works here, as the error is most likely raised in an async fashion / passed in to the connection callback.

The error that @Paisansang posted (`ConnectionError: Failed to connect to xxxxt:1433 in 5000ms`) leads me to think that the host / port configuration is not valid (or connecting fails because of a firewall setting).

@Paisansang can you verify that the server is reachable?

**Comment by IanChokS** [comment]
@Paisansang if you have Microsft SQL Server Management Studio, you can try to make sure that [https://www.habaneroconsulting.com/stories/insights/2015/tcpip-is-disabled-by-default-in-microsoft-sql-server-2014](TCP IP is enabled)  and that [https://sqlandme.com/2013/05/01/sql-server-finding-tcp-port-number-sql-instance-is-listening-on/](You have the correct port number in your configuration)

**Comment by JayakrishnanJK** [comment]
i am facing the same issue. While mssql server have some connection problem then the nodemon is getting crashed and my ap crashes. I have try ,catch blocks for error handling and its not handling the connection error and app gets crashed

**Comment by MichaelSun90** [comment]
Hi @JayakrishnanJK , can you kindly provide some connection config setups for your app?
From the error, it seems that server-side reset the connection. If this involved Azure connections, that may be caused by the balance loader detected an idle connection and put it into a collection of them. The connection itself may still be valid. You can try to add a callback function for connection.on('error',) to handle the error here.

**Comment by IanChokS** [comment]
@Paisansang @JayakrishnanJK , do you have any updates for us?

**Comment by VasilevVitalii** [comment]
I have this problem, simulate it by sending a "kill XX" from Management Studio. Here is the location causing the error:

![image](https://user-images.githubusercontent.com/41614640/71543052-5e6cde80-297f-11ea-9a42-9fdae76ed32b.png)

**Comment by MichaelSun90** [comment]
Hi @VasilevVitalii 
Can you show us your script that trigging this error? I just tried a simple script on my side, and before it sends the SQL query, I killed the connection from the SQL server management studio, and the program goes straight to socket error and terminated normally which I think is the expected behavior? 

This is my example: 
`let connection = new Connection(config);

connection.on('connect', (err) => {
    if (err) {
        console.log('connection error: ', err)
    } else {
        console.log('connected!')
       // I set a break point here, and kill the connection when the process hit the break point here. 
        sendQuery(); 
    }
})

connection.on('debug', function (text) {
    console.log(text);
});

connection.on('infoMessage', function (info) {
    console.log('state: ', info.state, ' | ', 'message: ', info.message)
})

function sendQuery() {
    console.log('sending query')
    let request = new Request('Select * From MyTable', (err, rowCount) => {
        if (err) {
            console.log('Request err: ', err);
        } else {
          console.log('done');
        }
    })

    let row = 1;
    request.on('row', function (columns) {
        console.log('row: ', row)
        columns.forEach(function (column) {
            if (column.value === null) {
                console.log('NULL');
            } else {
                console.log(column);
            }
        });
        row += 1;
    });

    connection.execSql(request);
}`

Maybe I missed something here. if you can provide a script, so I can try to reproduce the issue on my side, and I can continue the investigation from there.  

This is my state changelog:
![image](https://user-images.githubusercontent.com/47126816/71634699-fca4b280-2bd2-11ea-87a6-54cea3933804.png)

**Comment by VasilevVitalii** [comment]
Hi @MichaelSun90 
Sorry for the slow response - new year holidays.
Project, where I see error, use package **https://www.npmjs.com/package/mssql** (and it's use tedious). If I create a small test project with tedious and without mssql, I do not get error. Or something I don’t take into account in a small project, or the error is not in your package.

**Comment by IanChokS** [comment]
The error is most likely in mssql, as it's not actively maintained.
